name: cloudwatch-consumer-lambda CI job

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 'openjdk11'
        architecture: 'x64'
    - name: Build far Jar-file with Maven
      run: mvn clean package
